FROM golang:1.10-alpine3.8 AS multistage

RUN mkdir /app
ADD . /app/
WORKDIR /app/ascii-art-web/app
RUN go build

## MULTISTAGE TO RUN BUILT

FROM alpine:3.8

RUN apk --update upgrade
RUN apk add sqlite
RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2
RUN rm -rf /var/cache/apk/*

RUN mkdir /app
COPY --from=multistage /app/ /app/

WORKDIR /app/ascii-art-web/app
EXPOSE 8080:8080
CMD ["./app"]